### ISSUE TITLE
signal name

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/BNC_IDC#2]
Since this can be used with ADCs as well, maybe it would be better to rename `DAC_OUTP0` etc to something like `IDC0P`

**Comment by gkasprow** [comment]
OK, this release goes into production right now, so we can implement these changes. I'll ask guys if the PCB was sent to the print house.

**Comment by hartytp** [comment]
It's not a problem if you can't do this for the current revision.

**Comment by hartytp** [comment]
@gkasprow I've completed my design review for this PCB looks good! Ideally, let's fix the issues I've raised for this production round, but if that's a problem we can wait for some future round -- the changes aren't important.

**Comment by gkasprow** [comment]
fixed
