### ISSUE TITLE
mechanical

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/BNC_IDC#3]
@gkasprow you've probably already done this, but just to check :)

Did you check that all the mechanical issues to do with the panels were fixed
- https://github.com/sinara-hw/meta/issues/3
- https://github.com/sinara-hw/meta/issues/2
- and I think there was some previous issue to do with the nuts/cut-outs for the insulated BNCs

**Comment by gkasprow** [comment]
Yes, all these issues were addressed.
