### ISSUE TITLE
access to DNP components

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/BNC_IDC#4]
@hartytp right now access to the DNP components is lilited. They are fitted between BNC and CMC so replacement would be difficult. Maybe moving them to bottom side would be better? Of course they are more prone to mechanical damage...

**Comment by gkasprow** [comment]
How it looks like now:
![obraz](https://user-images.githubusercontent.com/4325054/43840831-001d149a-9b22-11e8-88bb-6f7fcd8247a1.png)

**Comment by gkasprow** [comment]
We can also make the board slightly longer.

**Comment by hartytp** [comment]
Let's keep them on the top side please.

I don't mind if they're a bit hard to access, since they won't be changed often. But, probably the best would be to make the PCB a little longer.

**Comment by gkasprow** [comment]
I enlarged the board a bit:
![obraz](https://user-images.githubusercontent.com/4325054/43845922-690f7a1e-9b2d-11e8-8731-74d1846d89a5.png)

**Comment by hartytp** [comment]
:+1: thanks
